<a href="https://colab.research.google.com/github/hrishabhxcode/Machine-Learning/blob/main/Data_Encoding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nominal / One Hot Encoding

In [ ]:
import pandas as  pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
#Create a Simple Dataframe

df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [ ]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [ ]:
encoder = OneHotEncoder()

In [ ]:
#perform fit and Transform

encoded = encoder.fit_transform(df[['color']]).toarray()

In [ ]:
import pandas as pd

encoder_df = pd.DataFrame(encoded , columns = encoder.get_feature_names_out())

In [ ]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0